random_seed: 2

# ---------------------------------------------
# Image delay (In milliseconds)
# ---------------------------------------------
image_delay_correction_factor: 0.98
study_phase_central_fixation_cross_delay: 1000
study_phase_to_be_studied_image_delay: 2000

test_phase_central_fixation_cross_delay: 1000
test_phase_catch_stimuli_image_delay: 5000