GAPED_animal_concerns_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/A/
GAPED_human_concerns_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/H/
GAPED_neutral_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/N/
GAPED_positive_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/P/
GAPED_snakes_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/Sn/
GAPED_spiders_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/Sp/
additional_animal_concerns_images:
- A036.bmp
- A037.bmp
- A041.bmp
- A001.bmp
- A113.bmp
- A118.bmp
- A064.bmp
- A047.bmp
- A018.bmp
- A048.bmp
additional_human_concerns_images:
- H091.bmp
- H039.bmp
- H123.bmp
- H060.bmp
- H022.bmp
- H081.bmp
- H014.bmp
- H009.bmp
- H084.bmp
- H079.bmp
additional_neutral_images:
- N046.bmp
- N086.bmp
- N030.bmp
- N079.bmp
- N031.bmp
- N109.bmp
- N068.bmp
- N080.bmp
- N077.bmp
- N065.bmp
- N081.bmp
- N066.bmp
- N002.bmp
- N020.bmp
- N061.bmp
- N104.bmp
- N088.bmp
- N092.bmp
- N003.bmp
- N089.bmp
- N023.bmp
- N098.bmp
- N035.bmp
- N025.bmp
- N100.bmp
- N011.bmp
- N090.bmp
- N073.bmp
- N038.bmp
- N033.bmp
- N013.bmp
- N093.bmp
- N027.bmp
- N034.bmp
- N101.bmp
- N108.bmp
- N105.bmp
- N094.bmp
- N043.bmp
- N044.bmp
additional_positive_images:
- P063.bmp
- P013.bmp
- P062.bmp
- P061.bmp
- P033.bmp
- P125.bmp
- P034.bmp
- P016.bmp
- P048.bmp
- P014.bmp
- P065.bmp
- P087.bmp
- P093.bmp
- P091.bmp
- P003.bmp
- P066.bmp
- P121.bmp
- P011.bmp
- P007.bmp
- P040.bmp
- P106.bmp
- P130.bmp
- P102.bmp
- P116.bmp
- P052.bmp
- P028.bmp
- P105.bmp
- P017.bmp
- P123.bmp
- P044.bmp
- P022.bmp
- P090.bmp
- P118.bmp
- P004.bmp
- P015.bmp
- P110.bmp
- P023.bmp
- P070.bmp
- P095.bmp
- P103.bmp
additional_snake_images:
- Sn043.bmp
- Sn073.bmp
- Sn109.bmp
- Sn129.bmp
- Sn071.bmp
- Sn103.bmp
- Sn011.bmp
- Sn089.bmp
- Sn082.bmp
- Sn019.bmp
additional_spider_images:
- Sp034.bmp
- Sp083.bmp
- Sp159.bmp
- Sp099.bmp
- Sp024.bmp
- Sp104.bmp
- Sp023.bmp
- Sp147.bmp
- Sp106.bmp
- Sp073.bmp
buffer_stimuli_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/GAPED_imagens/N/
catch_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/catch_images/
catch_stimuli_images_list:
- bird_caricature.jpeg
- camel_caricature.jpeg
- smiling_shark.jpeg
- squirrel_holding_a_gun.jpeg
- tiger_caricature.jpeg
catch_stimuli_images_path: /home/prietoab/sussuarana/clientes/davi/imagens/catch_images/
cross_image_name: cross.jpg
cross_image_path: /home/prietoab/sussuarana/clientes/davi/imagens/cross/
selected_animal_concerns_images:
- A106.bmp
- A017.bmp
- A112.bmp
- A088.bmp
- A077.bmp
- A080.bmp
- A068.bmp
- A131.bmp
- A123.bmp
- A076.bmp
selected_buffer_stimuli_images:
- N096.bmp
- N069.bmp
- N071.bmp
- N004.bmp
- N107.bmp
- N087.bmp
- N075.bmp
- N001.bmp
selected_human_concerns_images:
- H013.bmp
- H037.bmp
- H098.bmp
- H053.bmp
- H087.bmp
- H082.bmp
- H019.bmp
- H126.bmp
- H017.bmp
- H030.bmp
selected_neutral_images:
- N083.bmp
- N021.bmp
- N041.bmp
- N026.bmp
- N076.bmp
- N039.bmp
- N015.bmp
- N091.bmp
- N028.bmp
- N032.bmp
- N008.bmp
- N097.bmp
- N019.bmp
- N078.bmp
- N102.bmp
- N022.bmp
- N106.bmp
- N010.bmp
- N006.bmp
- N095.bmp
- N082.bmp
- N062.bmp
- N040.bmp
- N018.bmp
- N037.bmp
- N009.bmp
- N024.bmp
- N064.bmp
- N070.bmp
- N045.bmp
- N042.bmp
- N099.bmp
- N085.bmp
- N047.bmp
- N017.bmp
- N014.bmp
- N072.bmp
- N016.bmp
- N067.bmp
- N036.bmp
selected_positive_images:
- P067.bmp
- P097.bmp
- P088.bmp
- P006.bmp
- P069.bmp
- P020.bmp
- P055.bmp
- P075.bmp
- P043.bmp
- P074.bmp
- P081.bmp
- P073.bmp
- P029.bmp
- P084.bmp
- P046.bmp
- P099.bmp
- P042.bmp
- P049.bmp
- P050.bmp
- P089.bmp
- P027.bmp
- P038.bmp
- P077.bmp
- P109.bmp
- P031.bmp
- P053.bmp
- P064.bmp
- P086.bmp
- P072.bmp
- P101.bmp
- P025.bmp
- P112.bmp
- P092.bmp
- P113.bmp
- P058.bmp
- P012.bmp
- P114.bmp
- P082.bmp
- P100.bmp
- P119.bmp
selected_snake_images:
- Sn005.bmp
- Sn069.bmp
- Sn128.bmp
- Sn009.bmp
- Sn132.bmp
- Sn123.bmp
- Sn122.bmp
- Sn070.bmp
- Sn022.bmp
- Sn133.bmp
selected_spider_images:
- Sp117.bmp
- Sp107.bmp
- Sp094.bmp
- Sp014.bmp
- Sp001.bmp
- Sp137.bmp
- Sp009.bmp
- Sp140.bmp
- Sp158.bmp
- Sp062.bmp
user_id: 888
user_name: Test
user_random_seed: 789
